# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "es0d3X2zl4DLL8a2ZhZkD7ckT+qKrRsCWZo6AoiCSuo7w8HF7JI77tWSdYg3GshK9hXHXJzsqdnodX4nj+wSjlhBmgKNlxZJPKuBo3lB0C8T/cz1rNlcB8mUZlysNJnOHgYD2rlGGny+vaprCQ2iCmXOGWmQGMo5Qbv7gzWxddLpOR7hSzHbDNKuPS4px2TRx/XcSPhVNB98Lq43rcyaHBDm0EGlAdmCEYbaNkHAS08/vb16q65hXoX1nZc30i6+qFTscBnkAOU6Kl66G30a2Fa+to0xfOOtoA3/KxORi8FAwWdS8R1w+lha3T165K1WZOfQhxWsw6OtSVwHLn5TJI2gr8RFZFh5bCYkMfpRpfAkM+MLyBwf3Xr3QLTkvLAFLImUS5HLWYzwM2zh2Fvb2xginjTe50v5aR6B024qFpOyVR/ebS0y9IiktZ3ow8ADp9R1xr2IEaJbugDw3aItWgfvGy5H+OwdgTiPcK38I/cuJDylaauhmJfqi5FnjzAfEJfdzQGUkb0IW0729DUu6+TUAnn3MHHDRB55oKVNoszCw40D+Se9tkK/J59f6UYLbk9H7vuJX13YhgLjY7rqYAZEVE846gjy766DRN0Bz3zRcV1zTkCA8dEwqjrSBlkDgo5+yGw4sW6PQT1I+MieC5t/29xHqv2ZiIGc48lsfok="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda config --set show_channel_urls true
      conda update --yes conda
      conda install --yes conda-build=1.20.0 jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
