travis:
  secure:
    BINSTAR_TOKEN: SQW1rZf05Msfnavc4u1BJU1hro5IehETyhXknZpeefGdIIWChikYJz/6fMMJ5bDlGHDRxwxqnK0Qq1h4M9O+LJ9t06r8lKbc7WuNivuLfHeE3RlIgWb++RYx/3d9Qjhqup7cGUpbgK87W7Id/vofBGAgJw7K4ZQ5d4lU7Kq9s3jIJ4bXCUDCildyaQRoH5bwD89Zp4G4mfA2jb2mQjqv5bDOGn6WvWcM4Cs+W/W+CaMnlSeA4QyYF/LIQyG9J0LAitT/h1a41IegeWRb4tOnLfKCseP73B4BHGXjT3jARpobsNxSfosXpfs/FSMcchthV3979OspGVvrNiJn/S9sg9E4NryF2+5bQd5pMs0L0eHc5O5lGg6Lbu+WlIIVs+IctP182Mavsudfg03Ry6W+RC9OkAoEQYWD9OX711ZJH8rvNnqgvUPRxV8enzT/1Ivt2emrKbeOFijdGysUlGcDHD23YjK9UCJwcVkTjSwRFLJyvbMJxEgwTTOEjCHaf+QoNfPCiVdVJKjHoNvXVRrSprdoVOUj1DxwTw/klrax9VlUfc6b0fdlv/LiT2Bt5rJI7LhrDxVlVqtcH4c0sfNsPwD6wNA5i/qP0vHgTiA/y8m/41Jea8JxXJdcy+laBCoS+W3nQ9Hhr9apkclBhO9Fw1pGjhXuaQO4ldxAa25fm0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
