travis:
  secure:
    BINSTAR_TOKEN: es0d3X2zl4DLL8a2ZhZkD7ckT+qKrRsCWZo6AoiCSuo7w8HF7JI77tWSdYg3GshK9hXHXJzsqdnodX4nj+wSjlhBmgKNlxZJPKuBo3lB0C8T/cz1rNlcB8mUZlysNJnOHgYD2rlGGny+vaprCQ2iCmXOGWmQGMo5Qbv7gzWxddLpOR7hSzHbDNKuPS4px2TRx/XcSPhVNB98Lq43rcyaHBDm0EGlAdmCEYbaNkHAS08/vb16q65hXoX1nZc30i6+qFTscBnkAOU6Kl66G30a2Fa+to0xfOOtoA3/KxORi8FAwWdS8R1w+lha3T165K1WZOfQhxWsw6OtSVwHLn5TJI2gr8RFZFh5bCYkMfpRpfAkM+MLyBwf3Xr3QLTkvLAFLImUS5HLWYzwM2zh2Fvb2xginjTe50v5aR6B024qFpOyVR/ebS0y9IiktZ3ow8ADp9R1xr2IEaJbugDw3aItWgfvGy5H+OwdgTiPcK38I/cuJDylaauhmJfqi5FnjzAfEJfdzQGUkb0IW0729DUu6+TUAnn3MHHDRB55oKVNoszCw40D+Se9tkK/J59f6UYLbk9H7vuJX13YhgLjY7rqYAZEVE846gjy766DRN0Bz3zRcV1zTkCA8dEwqjrSBlkDgo5+yGw4sW6PQT1I+MieC5t/29xHqv2ZiIGc48lsfok=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
