appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: XyxqIoonWZrMvhM0ff+upBPUJ3lwBpIKDZGB1Ty97p14l8DB1VeQi3M9pyRVZPj0+uzuCpLbr4CYCNvE5OllayeM95MO0hFOiUloF47N7PNX72Qq0fkwLiPR8yLTt07rIwYlFoMdzA9FAOgBLlohfKmMbnIOBNKszd7+vurptbwdWXESYhHz7cAVN29hSRmH+8jCxtx586HQ1pJQ4ADxU11Bod01AYR+sHwa5PNwb/NDMmHjuNm/kruzpBjTVVFSJjqTNLvDvIIVqILkMe3I+1IZso1Pu0FXqmYnLxWLxqZuzD3EI3hmmKrkZPAx/7iGEhKFfOhctmyCn1cmxkmifT7+vBn2czg/mRqyTJDmVnRQOSKSebke3rELQai4Sy2cxwuIV8zzTTNpUjw4qq6W3jufOMuzlM5TLU5PFh0Qtg4mz68NfKm/HJpKlXDnshQeh+jAuJnz8s/87fM+pra5ySh/ONN8kGgCQQ2OQCdbyHDU3DB9PyOuHJVNpgjRpErb4WPwpUy8LB3QsH72VzCi3r5btE2ED8+/IkTb1FjgwFM14nYDsbus2Nwdt58WwaGovVvZ2AI+Aw1eYypQXgqC7651JIiw2OFqvhV02Rx8MIEGlzHGINf+wHOfUii6e9aFgP5CRLr9p3vg6uyi8UXTSK0gxVl9/Et6I31CPPYsrlo=}
